### ISSUE TITLE
Error when trying to plot a circle with add_patch

### ISSUE THREAD

**Issue by FrancoisMB** [jwass/mplleaflet#45]
I'm still trying to display a circle of fixed size in a leaflet map.

I tried with .add_artist() (see [here](https://github.com/jwass/mplleaflet/issues/44)) and I'm now trying with `.add_patch()`. Here is what I'm doing : 

```
import mplleaflet
import matplotlib.pyplot as plt
import matplotlib as mpl

fig, ax = plt.subplots()
x = 2.363561
y = 48.951918
r = 20
circle1 = mpl.patches.Circle((x,y), radius=r)
circle2= plt.Circle((x, y), r, color='r')

#ax.add_patch(circle1)
#ax.add_patch(circle2) 

mplleaflet.show(fig=ax.figure)
```

You can try to uncomment one of the two commented lines, it doesn't matter which line is uncommented, the same error pops.

Here is the trace I get :

```
Traceback (most recent call last):

  File "<ipython-input-81-1fdd7f4a9d12>", line 16, in <module>
    mplleaflet.show(fig = ax.figure)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mplleaflet\_display.py", line 180, in show
    save_html(fig, fileobj=f, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mplleaflet\_display.py", line 131, in save_html
    html = fig_to_html(fig, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mplleaflet\_display.py", line 84, in fig_to_html
    exporter.run(fig)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mplleaflet\mplexporter\exporter.py", line 51, in run
    self.crawl_fig(fig)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mplleaflet\mplexporter\exporter.py", line 118, in crawl_fig
    self.crawl_ax(ax)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mplleaflet\mplexporter\exporter.py", line 138, in crawl_ax
    self.draw_patch(ax, patch)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mplleaflet\mplexporter\exporter.py", line 227, in draw_patch
    mplobj=patch)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mplleaflet\leaflet_renderer.py", line 125, in draw_path
    rings = list(iter_rings(data, pathcodes))

  File "C:\ProgramData\Anaconda3\lib\site-packages\mplleaflet\utils.py", line 14, in iter_rings
    raise ValueError('Unrecognized code: {}'.format(code))

ValueError: Unrecognized code: C
```

______________________________________________________________

Just to see what would happen, I tried doing the same thing than [this](https://github.com/jwass/mplleaflet/issues/40#issuecomment-327276786), which is changing 

`        elif code == 'L': ring.append(point)`

to 

`        elif code == 'L' or code == 'Z' or code == 'S' or code == 'C': ring.append(point)`

in mplleaflet\utils.py", line 11 and 12. Here is what I got : 

![image](https://user-images.githubusercontent.com/15570583/30692053-27d84a7c-9eca-11e7-8f2b-5348d09378e7.png)

**Comment by Agnpalm** [comment]
I have the same issue, I'm pretty sure it's because of incomplete SVG handling. I posted a comment about it in the other issue with more info.
https://github.com/jwass/mplleaflet/issues/40#issuecomment-372896486

There's even a [comment ](https://github.com/jwass/mplleaflet/blob/6f0945189b0bc4d140171b6529749e3ac1f817a1/mplleaflet/utils.py#L7)about it in the code from four years ago.

**Comment by nwpulver** [comment]
Same issue here but with plotting ellipses. 

```
fig2 = plt.figure(0)
ax2 = fig2.add_subplot(111)
for point, w, h in zip(zip(gps_disp['Lon'], gps_disp['Lat']), normal_sigmaE, normal_sigmaN):
    ellipse = Ellipse(xy=point, width=w/10, height=h/10,
                      edgecolor='black', alpha=.5,)
    ax2.add_patch(ellipse)

ax2.plot()
```

Here I just want to export  to a geojson but I get the same error regardless.
